<!DOCTYPE html>
<html>
<head>
	<?php echo $this->headTitle() ?>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<link href="<?php echo $this->baseUrl('css/bootstrap.css') ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->baseUrl('css/style.css') ?>" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('js/flotr2.min.js') ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap.min.js') ?>"></script>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="index.html">SAP</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li>
						<a href="index.html">Dashboard</a>
					</li>
					<li>
						<a href="streams.html">Streams</a>
					</li>
					<li>
						<a href="#">Media Files</a>
					</li>
					<li>
						<a href="#">Users</a>
					</li>
					<li>
						<a href="#">Settings</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<?php echo $this->layout()->content ?>
</div>
</body>
</html>
