<h3>Overview</h3>
<table class="table table-striped table-condensed">
	<thead>
	<tr>
		<th>#<i class="icon-arrow-down"></i></th>
		<th>Stream Name</th>
		<th>Listeners</th>
		<th>Bitrate</th>
		<th>Port</th>
		<th>Available Space</th>
		<th>Uptime</th>
		<th>Status</th>
		<th>Listen</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->streams as $stream): ?>
	<?php /** @var $stream Application_Model_Server */ ?>
	<tr>
		<td><?= $this->escape($stream->getId()) ?></td>
		<td><?= $this->escape($stream->getName()) ?></td>
		<td><?= $this->escape($stream->getCurrentListeners()) ?>/<?= $this->escape($stream->getMaxListeners()) ?></td>
		<td><?= $this->escape($stream->getBitrate()) ?></td>
		<td><?= $this->escape($stream->getPort()) ?></td>
		<td><?= $this->escape($stream->getAvailableSpace()) ?></td>
		<td><?= $this->escape($stream->getUptime()) ?></td>
		<td>
			<?php if ($stream->isOnline()): ?>
			<i class="icon-ok"></i>Online
			<?php else: ?>
			<i class="icon-remove"></i>Offline
			<?php endif; ?>
		</td>
		<td>
			<a href="awesome.pls" class="icon-play"></a>
		</td>
	</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<div class="pagination pagination-right">
	<ul>
		<li class="disabled"><a href="#">«</a></li>
		<li class="active"><a href="#">1</a></li>
		<li><a href="#">2</a></li>
		<li><a href="#">3</a></li>
		<li><a href="#">4</a></li>
		<li><a href="#">»</a></li>
	</ul>
</div>