<?php
/**
 * User: peaceman
 * Date: 4/17/12
 * Time: 9:10 PM
 */
?>
<h3>user listing</h3>
	<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'create')) ?>">Create user</a>
<table>
	<thead>
	<tr>
		<th>id</th>
		<th>username</th>
		<th>email</th>
		<th>created_at</th>
		<th>updated_at</th>
		<th>#</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->users as $user): ?>
		<?php /** @var $user Application_Model_User */ ?>
		<tr>
			<td><?php echo $this->escape($user->getId()) ?></td>
			<td><?php echo $this->escape($user->getUsername()) ?></td>
			<td><?php echo $this->escape($user->getEmail()) ?></td>
			<td><?php echo $this->escape($user->getCreatedAt() !== null ? $user->getCreatedAt()->format('d.m.Y H:i:s') : '-') ?></td>
			<td><?php echo $this->escape($user->getUpdatedAt() !== null ? $user->getUpdatedAt()->format('d.m.Y H:i:s') : '-') ?></td>
			<td>
				<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'details', 'id' => $user->getId())) ?>">Details</a>
				<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'edit', 'id' => $user->getId())) ?>">Edit</a>
				<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete', 'id' => $user->getId())) ?>">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
